---

options:
  env:
    - 'IMAGE_PATH=us-central1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/user-service:$SHORT_SHA'

steps:
  - id: 'Maven'
    name: 'maven:3-jdk-11'
    entrypoint: mvn
    args: ['clean', 'install']

  - id: 'Docker build & push'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args: ['-c', 'docker build -t "$${IMAGE_PATH}" . && docker push "$${IMAGE_PATH}"']

  - id: 'K8s deployment'
    name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: bash
    #args: ['-c', 'cat k8s-deployment.yaml | sed "s/{app_version}/$SHORT_SHA/g" k8s-deployment.yaml | kubectl apply -f -']
    args:
      - '-c'
      - |
        echo $SHORT_SHA
        gcloud container clusters get-credentials hello-cloudbuild
        cat k8s-deployment.yaml | sed "s/COMMIT_ID/$SHORT_SHA/g" k8s-deployment.yaml | kubectl apply -f -
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=hello-cloudbuild'
