---

options:
  env:
    - 'IMAGE_PATH=us-central1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/user-service:$SHORT_SHA'

steps:
  - id: 'Maven'
    name: 'maven:3-jdk-11'
    entrypoint: mvn
    args: ['clean', 'install']

  - id: 'Docker build & push'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args: ['-c', 'docker build -t "$${IMAGE_PATH}" . && docker push "$${IMAGE_PATH}"']

  - id: 'K8s deployment'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args: ['-c', 'apt-get install kubectl', 'cat k8s-deployment.yaml | sed "s/{app_version}/$SHORT_SHA/g" k8s-deployment.yaml | kubectl apply -f -']
