apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app  #This should match with .template.metadata.labels
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80   #At this port nginx will be running

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: nginx-app  #This should be same as labels of pod template
  ports:
  - port: 8777    #Port where we want to use access nginx
    targetPort: 80    #Optinal. Port where nginx is actually running in container(s) inside cluster
