
spring:
  application:
    name: user-service

#management.endpoints.web.exposure.include: "*"
#management.endpoint.health.group.custom.show-details: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

user-service:
  version: v1.0.3
